# Snooker Training Data Pipeline Configuration

# Input/Output directories
raw_videos_dir: "data/raw_videos"          # Directory to store downloaded YouTube videos
processed_videos_dir: "data/processed_videos"  # Directory for preprocessed videos
output_dir: "data/training_dataset"                  # Output directory for the final dataset

# YouTube download settings
youtube_urls: "youtube_urls.txt"  # File containing YouTube URLs (one per line)
cookies_file: "youtube_cookies.txt"  # Optional: Path to cookies file for YouTube

# Video processing settings
target_fps: 30  # Target FPS for processed videos
min_table_visibility: 0.4  # Minimum table visibility ratio (0-1)
max_frames_per_video: 120  # Maximum number of frames to extract from each video

# Frame extraction settings
frame_interval: 18  # Extract one frame every N frames

# Dataset split ratios (should sum to 1.0)
train_ratio: 0.7
val_ratio: 0.15
test_ratio: 0.15
